version: '3.2'

services:
  users:
    image: ftc8404/auth-api-users:latest
    # ports:
    # - "8080:8080/tcp"
    depends_on:
    - kafka
    - mongo
    - eureka
    hostname: users
    # environment:
    #   LOGGING_LEVEL_ROOT: DEBUG
    networks:
    - kafka-net

networks:
  kafka-net:
    driver: overlay
