server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: orders
  data:
    mongodb:
      uri: mongodb://localhost:27017/users
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      users-pals8404: users.pals8404.change
    consumer:
      group-id: cases
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://mongo:27017/users
  kafka:
    bootstrap-servers: kafka:9092
logging:
  level:
    root: INFO
