apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-release
  labels:
    app: mongodb-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-release
  template:
    metadata:
      labels:
        app: mongodb-release
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: mongodb-release
        image: mongo:latest
        env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   value: "root"
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   value: "storefront-root-password"
        # command: ["--smallfiles"]
        ports:
        - containerPort: 27017
      restartPolicy: Always
